### ISSUE TITLE
A simple README.md grammar error!

### ISSUE THREAD

**Issue by rzmk** [rutgersesports/discord-bot#1]
A simple error in our README.md where we should add a word "**to**" in the following sentence:

![image](https://user-images.githubusercontent.com/30333942/127868104-aa93ae27-9938-41fe-b87f-e09a2803ca48.png)

Edit the README.md by changing the sentence to:
Send feature requests to [our Discord](https://discord.gg/RutgersEsports)!

**Comment by kadatatlukishore** [comment]
hello @rzmk Can I do this ?

**Comment by rzmk** [comment]
> hello @rzmk Can I do this ?

Sure go ahead! Make a fork, make your changes as a commit and push, and then submit your pull request!
